language: node_js
before_script:
  - npm ci
script:
  - echo "Deploy whiteboard2code..."
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project whiteboard-to-code --token $FIREBASE_TOKEN
